### ISSUE TITLE
Pivot calibration: erroneous mixing algorithms by recursion

### ISSUE THREAD

**Issue by Lecrapouille** [SciKit-Surgery/scikit-surgerycalibration#58]
Hello, I'm not a good Python programmer, but it seems that the pivot_calibration_with_ransac function is calling badly its recursion:

https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L11

will call https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L66

that will call https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L116

that will call https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L157 with implicit `configuration=None` as parameter that will call https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L55

and https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L58

but since https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L42

the https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/549a53451752979c1e1c7c33c28686949b8b1957/sksurgerycalibration/algorithms/pivot.py#L60 is not called

I've not traced calls (as noob in Python is this kind of tool exists ?), this is a simple "manual" code review, I may be wrong. I guess you have forgotten to pass configuration in the recursive calls. Finally, your recursive algorithm is complex to understand: I think pivot_calibration_with_ransac shall only call pivot_calibration_with_ransac but not the base function pivot_calibration.

**Comment by thompson318** [comment]
Thanks for raising this. I'm away this week so have assigned @mxochicale to take a look first. @mxochicale can you please take a look? @MattClarkson might be able to help too as I think he was the main author on this.

**Comment by thompson318** [comment]
I've had a look at this now. I think it is confusion caused by our overly complex recursion (which I don't think is actually recursion). My understanding is that pivot_calibration is a wrapper that will call one of three methods (pivot_calibration_aos, pivot_calibration_ransac, or pivot_calibration_sphere_fitting). 
pivot_calibration_ransac calls pivot_calibration_aos multiple times to iteratively find an optimal solution (i.e. pivot_calibration_ransac is not meant to call itself (recurse)). 
I've clarified that in the code see https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/a1f455636fe8ead79d3a3c665ad2592a83925c11/sksurgerycalibration/algorithms/pivot.py#L157 and https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/a1f455636fe8ead79d3a3c665ad2592a83925c11/sksurgerycalibration/algorithms/pivot.py#L183
I hope that makes sense. If so I'll create a pull request for it.

**Comment by Lecrapouille** [comment]
> My understanding is that pivot_calibration is a wrapper that will call one of three methods (pivot_calibration_aos, pivot_calibration_ransac, or pivot_calibration_sphere_fitting).

I agree with you.

> pivot_calibration_ransac calls pivot_calibration_aos multiple times to iteratively find an optimal solution (i.e. pivot_calibration_ransac is not meant to call itself (recurse)).

I agree with you.

> I hope that makes sense. If so I'll create a pull request for it.

The fix looks good to me. Probably you will have to also update unit tests.
